# Generated by Django 3.2.6 on 2024-09-30 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
                ('saldoPendiente', models.FloatField()),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta', to='estudiante.estudiante')),
            ],
        ),
    ]
