# Generated by Django 3.2.6 on 2024-09-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoEstudiante', models.CharField(max_length=100)),
                ('fechaNacimiento', models.DateTimeField()),
                ('grado', models.CharField(max_length=100)),
            ],
        ),
    ]
