# Generated by Django 3.2.6 on 2024-09-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuenta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaEmision', models.DateTimeField()),
                ('descripcion', models.CharField(max_length=50)),
                ('cuentas', models.ManyToManyField(related_name='reportes', to='cuenta.Cuenta')),
            ],
        ),
    ]
