# Generated by Django 5.1.3 on 2024-11-14 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responsableEconomico', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsableeconomico',
            old_name='documento_identidad',
            new_name='documentoIdentidad',
        ),
        migrations.RemoveField(
            model_name='responsableeconomico',
            name='relacionConEstudiante',
        ),
    ]
